services:
  app:
    build:
      context: .
      target: app
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: ["npm", "run", "start"]
      
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb:11.2.2
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/database/data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]      
      interval: 5s
      timeout: 20s
      retries: 10
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      mariadb:
        condition: service_healthy
