services:
  app:
    image: ghcr.io/alexispet/final-test-theotruvelot/app:develop
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    command: ["npm", "run", "start"]
    networks:
      - frontend
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.develop-app-1.rule=Host(`dev.theotruvelot.fr`)"
      - "traefik.http.routers.develop-app-1.entrypoints=websecure"
      - "traefik.http.routers.develop-app-1.tls.certresolver=myresolver"
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb:11.2.2
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/database/data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]      
      interval: 5s
      timeout: 20s
      retries: 10

networks:
  frontend:
    external: true
    name: custom_frontend
  backend: