services:
  app:
    build:
      context: .
      target: release
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: ["npm", "run", "start"]
 