---
- name: Add docker
  hosts: webservers
  remote_user: admin
  become: true
  become_method: sudo

  tasks:
  - name: install dependencies
    apt:
      name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - software-properties-common
      state: latest
      update_cache: yes
  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: add docker repository to apt
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: install docker
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: latest
      update_cache: yes        
  - name: add user to docker group
    user:
      name: admin
      groups: docker
      append: yes
  - name: check docker status
    service:
      name: docker
      state: started
      enabled: yes
  - name: create folders
    file:
      path: "/home/admin/{{ env }}"
      state: directory
      owner: admin
      group: admin
      mode: '0755'
  - name: create files
    file:
      path: "/home/admin/{{ env }}/.env"
      state: touch
      owner: admin
      group: admin
      mode: '0755'
  - name: write in files
    blockinfile:
      path: "/home/admin/{{ env }}/.env"
      block: |
      DB_HOST={{ DB_HOST }}  
      DB_DATABASE={{ DB_DATABASE }}
      DB_PASSWORD={{ DB_PASSWORD }}
      DB_USER={{ DB_USER }}
      MYSQL_RANDOM_ROOT_PASSWORD={{ MYSQL_RANDOM_ROOT_PASSWORD }}
  - name: send by scp docker-compose file to remote host
    copy:
      src: /home/runner/work/final-test-theotruvelot/final-test-theotruvelot/docker-compose.global.yml
      dest: /home/admin/docker-compose.global.yml
      owner: admin
      group: admin
      mode: '0755'
  - name: send by scp docker-compose file to remote host
    copy:
      src: /home/runner/work/final-test-theotruvelot/final-test-theotruvelot/docker-compose.{{ env }}.yml
      dest: /home/admin/{{ env }}/docker-compose.{{ env }}.yml
      owner: admin
      group: admin
      mode: '0755'
  - name: run docker-compose global
    command: docker compose -f /home/admin/docker-compose.global.yml up -d
    args:
      chdir: /home/admin
  - name: run docker-compose {{ env }}
    command: docker compose -f /home/admin/{{ env }}/docker-compose.{{ env }}.yml up -d
    args:
      chdir: /home/admin/{{ env }}
  

  