name: ansible
on: [workflow_dispatch]


jobs:
    triger-ansible:
        environment: ${{ github.ref_name }}
        runs-on: ubuntu-latest
        if: github.ref_name == 'develop' || github.ref_name == 'main'
        steps:
            - name: Checkout
              uses: actions/checkout@v4  
            - name: Run playbook
              uses: dawidd6/action-ansible-playbook@v2
              with:
                playbook: ansible.playbook.yml
                inventory: inventory.ini
                directory: ./ansible
                key: ${{secrets.SSH_PRIVATE_KEY}}
                options:
                    --inventory inventory.ini
                    --extra-vars "env=${{github.ref_name}} DB_HOST=${{secrets.DB_HOST}} DB_DATABASE=${{secrets.DB_DATABASE}} DB_PASSWORD=${{secrets.DB_PASSWORD}} DB_USER=${{secrets.DB_USER}}"
            - name: Shoutrrr
              uses: containrrr/shoutrrr-action@v1
              with:
                url: ${{ secrets.WEBHOOK_URL }}
                title: Deployed on server ${{github.ref_name}} 
                message: commit ${{github.sha}} by ${{github.actor}} was deployed on server
