name: build

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on: [push]
jobs:
  tests:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env: 
      MYSQL_RANDOM_ROOT_PASSWORD: ${{ secrets.MYSQL_RANDOM_ROOT_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d --wait
      - run: docker compose exec app npm run test 
        
  security:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  eslint:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Install dependencies
          run: npm ci
        - name: Run ESLint
          run: npx eslint . --ext .js
  build-docker-production:
    runs-on: ubuntu-latest
    needs: [security, eslint]
    if: github.ref_name == 'main'
    environment: 
        name: ${{ github.ref_name }}
        url: https://prod.theotruvelot.fr
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tag,labels) for docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/app
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  build-docker-development:
    runs-on: ubuntu-latest
    needs: [security, eslint]
    if: github.ref_name == 'develop'
    environment:
        name: ${{ github.ref_name }}
        url: https://dev.theotruvelot.fr
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tag,labels) for docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/app
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}